import type { NextPage } from 'next';
import Head from 'next/head';
import { dehydrate, QueryClient, useQuery } from 'react-query';

const getCategories = async () => {
  try {
    const res = await fetch('https://www.themealdb.com/api/json/v1/1/categories.php');
    return res.json();
  } catch (err) {
    console.log(err);
    return err;
  }
};

const Home: NextPage = () => {
  const { data } = useQuery('categories', getCategories);

  console.log(data);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main></main>
    </div>
  );
};

export async function getStaticProps() {
  const queryClient = new QueryClient();

  await queryClient.prefetchQuery('categories', getCategories);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
}

export default Home;
